version: '3.8'

services:
  integration_db:
    image: postgres:15-alpine
    container_name: integration_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: integration_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - integration_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  integration_postgres_data:
