import re
import logging
import xml.etree.ElementTree as ET
from typing import Dict, Any, Optional

logger = logging.getLogger("mapping")

class ValidationError(Exception):
    """Raised when record validation fails during mapping."""
    pass

# Helper to validate email formats
EMAIL_REGEX = re.compile(r"^[^@]+@[^@]+\.[^@]+$")

def validate_unified_record(record: Dict[str, Any]):
    """Enforces basic structural rules on the mapped data."""
    if not record.get("external_id"):
        raise ValidationError("Missing external_id identifier.")
    if not record.get("name") or not record["name"].strip():
        raise ValidationError("Missing or empty customer name.")
    if not record.get("email") or not EMAIL_REGEX.match(record["email"]):
        raise ValidationError(f"Invalid or missing email address: {record.get('email')}")
    try:
        record["balance"] = float(record.get("balance", 0.0))
    except (ValueError, TypeError):
        raise ValidationError(f"Invalid balance format: {record.get('balance')}")
    
    # Normalize status values
    status = str(record.get("status", "active")).strip().lower()
    if status in ["active", "true", "completed", "enabled", "1"]:
        record["status"] = "active"
    else:
        record["status"] = "suspended"

def map_rest_payload(raw_json: Dict[str, Any]) -> Dict[str, Any]:
    """Maps JSON record from REST mock CRM."""
    mapped = {
        "external_id": raw_json.get("id"),
        "name": raw_json.get("name"),
        "email": raw_json.get("email"),
        "balance": raw_json.get("balance"),
        "status": "active" if raw_json.get("active") is True else "suspended"
    }
    validate_unified_record(mapped)
    return mapped

def map_xml_element(element: ET.Element) -> Dict[str, Any]:
    """Maps XML element from Billing System accounts."""
    try:
        external_id = element.findtext("id")
        name = element.findtext("name")
        email = element.findtext("email")
        balance = element.findtext("balance")
        status = element.findtext("status")
    except Exception as e:
        raise ValidationError(f"XML Parsing structural failure: {e}")

    mapped = {
        "external_id": external_id,
        "name": name,
        "email": email,
        "balance": balance,
        "status": status
    }
    validate_unified_record(mapped)
    return mapped

def map_csv_row(row: Dict[str, str]) -> Dict[str, Any]:
    """Maps CSV values parsed from file uploads."""
    mapped = {
        "external_id": row.get("customer_id"),
        "name": row.get("name"),
        "email": row.get("email"),
        "balance": row.get("balance"),
        "status": row.get("status")
    }
    validate_unified_record(mapped)
    return mapped

def map_webhook_payload(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Maps JSON webhook payloads generated by external gateway events."""
    data = payload.get("data", {})
    mapped = {
        "external_id": data.get("id"),
        "name": data.get("name"),
        "email": data.get("email"),
        "balance": data.get("amount"),
        "status": "active" if data.get("status") == "completed" else "suspended"
    }
    validate_unified_record(mapped)
    return mapped
